package lib.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static lib.Ingredient.*;
import lib.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.07.07 18:33:01 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class IngredientTest {



  // Generated by ComTest BEGIN
  /** testGetId43 */
  @Test
  public void testGetId43() {    // Ingredient: 43
    Ingredient i = new Ingredient(1, "peruna"); 
    assertEquals("From: Ingredient line: 45", 1, i.getId()); 
    Ingredient j = new Ingredient(2, "maito"); 
    assertEquals("From: Ingredient line: 47", 2, j.getId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetName56 */
  @Test
  public void testGetName56() {    // Ingredient: 56
    Ingredient i = new Ingredient(1, "peruna"); 
    assertEquals("From: Ingredient line: 58", "Peruna", i.getName()); 
    Ingredient j = new Ingredient(2, "maito"); 
    assertEquals("From: Ingredient line: 60", "Maito", j.getName()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse77 */
  @Test
  public void testParse77() {    // Ingredient: 77
    try {
    Ingredient i = Ingredient.parse("1 | peruna"); 
    assertEquals("From: Ingredient line: 80", 1, i.getId()); 
    i = Ingredient.parse("100 | maitojauhe"); 
    assertEquals("From: Ingredient line: 82", 100, i.getId()); 
    i = Ingredient.parse(""); 
    assertEquals("From: Ingredient line: 84", 100, i.getId()); 
    } catch (ParseException e) {
    System.out.println("Caught ParseException"); 
    }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNextId112 */
  @Test
  public void testGetNextId112() {    // Ingredient: 112
    assertEquals("From: Ingredient line: 113", 1, Ingredient.getNextId()); 
    Ingredient i = new Ingredient(5, "peruna"); 
    assertEquals("From: Ingredient line: 115", 1, Ingredient.getNextId()); 
    i = new Ingredient(); 
    assertEquals("From: Ingredient line: 117", 2, Ingredient.getNextId()); 
    assertEquals("From: Ingredient line: 118", 1, i.getId()); 
  } // Generated by ComTest END
}