package lib.test;
// Generated by ComTest BEGIN
import java.util.Arrays;
import static org.junit.Assert.*;
import org.junit.*;
import lib.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.07.06 16:36:35 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class IngredientsTest {



  // Generated by ComTest BEGIN
  /** testGetRows77 */
  @Test
  public void testGetRows77() {    // Ingredients: 77
    Ingredients i = new Ingredients(3,3); 
    assertEquals("From: Ingredients line: 79", 3, i.getRows()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToArray97 */
  @Test
  public void testToArray97() {    // Ingredients: 97
    Ingredients i = new Ingredients(3, 1); 
    i.put(new Ingredient(1, "peruna")); 
    assertEquals("From: Ingredients line: 101", "[1 | peruna, null, null]", Arrays.toString(i.toArray())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGet127 */
  @Test
  public void testGet127() {    // Ingredients: 127
    Ingredients i = new Ingredients(3,1); 
    i.put(new Ingredient(1, "peruna")); 
    assertEquals("From: Ingredients line: 130", "1 | peruna", i.get(1).toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGet147 */
  @Test
  public void testGet147() {    // Ingredients: 147
    Ingredients i = new Ingredients(3,1); 
    i.put(new Ingredient(1, "peruna")); 
    assertEquals("From: Ingredients line: 150", "1 | peruna", i.get("peruna").toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testContainsValue167 */
  @Test
  public void testContainsValue167() {    // Ingredients: 167
    Ingredients i = new Ingredients(3,1); 
    Ingredient j = new Ingredient(1, "peruna"); 
    assertEquals("From: Ingredients line: 170", false, i.containsValue(j)); 
    i.put(j); assertEquals("From: Ingredients line: 171", true, i.containsValue(j)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testPut182 */
  @Test
  public void testPut182() {    // Ingredients: 182
    Ingredients i = new Ingredients(3, 1); 
    assertEquals("From: Ingredients line: 184", 0, i.count()); 
    i.put(new Ingredient()); assertEquals("From: Ingredients line: 185", 1, i.count()); 
    i.put(new Ingredient()); 
    i.put(new Ingredient()); assertEquals("From: Ingredients line: 187", 3, i.count()); 
    i.put(new Ingredient()); assertEquals("From: Ingredients line: 188", 3, i.count()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRemove211 */
  @Test
  public void testRemove211() {    // Ingredients: 211
    Ingredients i = new Ingredients(); 
    i.put(new Ingredient(1, "Liha")); 
    i.put(new Ingredient(2, "Peruna")); 
    assertEquals("From: Ingredients line: 215", 2, i.count()); 
    i.remove(3); assertEquals("From: Ingredients line: 216", 2, i.count()); 
    i.remove(2); assertEquals("From: Ingredients line: 217", 1, i.count()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testCount239 */
  @Test
  public void testCount239() {    // Ingredients: 239
    Ingredients i = new Ingredients(); 
    i.put(new Ingredient()); assertEquals("From: Ingredients line: 241", 1, i.count()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSwap374 */
  @Test
  public void testSwap374() {    // Ingredients: 374
    Ingredients i = new Ingredients(3, 1); 
    i.put(new Ingredient()); 
    assertEquals("From: Ingredients line: 377", false, i.getFromIndexes(0,0) == null); 
    assertEquals("From: Ingredients line: 378", true, i.getFromIndexes(1,0) == null); 
    i.swap(0,0,1,0); 
    assertEquals("From: Ingredients line: 380", true, i.getFromIndexes(0,0) == null); 
    assertEquals("From: Ingredients line: 381", false, i.getFromIndexes(1,0) == null); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testHasNull400 */
  @Test
  public void testHasNull400() {    // Ingredients: 400
    Ingredients i = new Ingredients(3, 1); 
    assertEquals("From: Ingredients line: 402", true, i.hasNull()); 
    i.put(new Ingredient()); assertEquals("From: Ingredients line: 403", true, i.hasNull()); 
    i.put(new Ingredient()); i.put(new Ingredient()); 
    assertEquals("From: Ingredients line: 405", false, i.hasNull()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetFromIndexes422 */
  @Test
  public void testGetFromIndexes422() {    // Ingredients: 422
    Ingredients i = new Ingredients(3,1); 
    Ingredient j = new Ingredient(); 
    i.put(j); assertEquals("From: Ingredients line: 425", false, i.getFromIndexes(0,0) == null); 
    assertEquals("From: Ingredients line: 426", true, i.getFromIndexes(1,0) == null); 
  } // Generated by ComTest END
}