package lib.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static lib.Recipe.*;
import lib.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.07.07 20:57:39 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RecipeTest {



  // Generated by ComTest BEGIN
  /** testRecipe27 */
  @Test
  public void testRecipe27() {    // Recipe: 27
    Recipe r = new Recipe(); 
    assertEquals("From: Recipe line: 29", 1, r.getId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRecipe51 */
  @Test
  public void testRecipe51() {    // Recipe: 51
    Recipe r = new Recipe(1, "perunasalaatti", "atria", "suomi", "p‰‰ruoka", false, "ohje", null); 
    assertEquals("From: Recipe line: 53", "1 | perunasalaatti | atria | suomi | p‰‰ruoka | ohje", r.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetId94 */
  @Test
  public void testGetId94() {    // Recipe: 94
    Recipe r = new Recipe(1, "perunasalaatti", "atria", "suomi", "p‰‰ruoka", false, "ohje", null); 
    assertEquals("From: Recipe line: 96", 1, r.getId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testSetNextId107 */
  @Test
  public void testSetNextId107() {    // Recipe: 107
    Recipe.setNextId(6); 
    Recipe r = new Recipe(); 
    assertEquals("From: Recipe line: 110", 7, r.getId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testReplaceIngredient157 */
  @Test
  public void testReplaceIngredient157() {    // Recipe: 157
    Recipe r = new Recipe(); 
    Ingredient i = new Ingredient(1, "peruna"); 
    r.addIngredient(i); assertEquals("From: Recipe line: 160", "1 | peruna", r.getIngredients().get(0).toString()); 
    r.replaceIngredient(i, new Ingredient(2, "maito")); 
    assertEquals("From: Recipe line: 162", "2 | maito", r.getIngredients().get(0).toString()); 
  } // Generated by ComTest END
}