package lib.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;

import lib.ParseException;

import static lib.Relation.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.07.24 18:26:04 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RelationTest {



  // Generated by ComTest BEGIN
  /** testParse45 */
  @Test
  public void testParse45() {    // Relation: 45
    try {
    assertEquals("From: Relation line: 47", "1 | 1", parse("1 | 1").toString()); 
    } catch (ParseException e) {
    System.out.println(e); 
    }
  } // Generated by ComTest END
}